import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {build} from 'esbuild';
async function moduleAt(entry){const result=await build({entryPoints:[entry],bundle:true,write:false,platform:'node',format:'esm',target:'node24'});return import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));}
const {FarmCore}=await moduleAt('core/bridge.ts');
const {taskView,playerText,actionSummary,plotName}=await moduleAt('assets/scripts/view/FarmPresentation.ts');
const {PanelStack}=await moduleAt('assets/scripts/view/PanelStack.ts');
const {districtOf,districtOrigin,localPlotOf,plotAtDistrict,plotPosition,cameraForDistrict,districtAtCamera,HOME_PLOT_ID}=await moduleAt('assets/scripts/view/FarmDistrict.ts');
const {farmUnitOf,farmUnitStart,farmLocalOf}=await moduleAt('core/src/game/model/farm-coordinates.ts');
const {buildHudViewModel,nextTaskText,plotTitle:viewTitle}=await moduleAt('assets/scripts/presentation/FarmViewModel.ts');
const {WorldViewPreferences,WORLD_VIEW_PREFERENCES_KEY}=await moduleAt('assets/scripts/view/world/WorldViewPreferences.ts');
const {WorldViewRegistry,WORLD_VIEW_VERSIONS}=await moduleAt('assets/scripts/view/world/WorldViewRegistry.ts');
const {MAP_LAYOUT,boardTileSlot}=await moduleAt('assets/scripts/view/world/current/CurrentMapLayout.ts');
assert.equal(HOME_PLOT_ID,'p2q2');
assert.equal(plotName('p1q1'),'田地 1·1');
assert.equal(plotName('p0q2'),'田地 0·2');
assert.equal(plotName('p-1q2'),'田地 -1·2');
assert.deepEqual(plotPosition(2,2),{x:0,y:0},'farmhouse and home field must anchor the world origin');
for(const value of [-7,-2,-1,0,1,2,3,4,8]){
  const district=districtOf(value,2);
  assert.equal(district.x,farmUnitOf(value));
  assert.equal(districtOrigin(district).x,farmUnitStart(value));
  assert.equal(localPlotOf(value,2).x,farmLocalOf(value));
  assert.deepEqual(plotAtDistrict(district,localPlotOf(value,2)),{x:value,y:2});
}
const fieldbook=JSON.parse(await readFile('assets/resources/art-packs/fieldbook/manifest.json','utf8'));
assert.equal(fieldbook.images['board.home']?.file,'board-home.png');
for(const name of ['field','calendar','basket','more','back','close','next','leaf','coin','food','pressure'])
  assert.ok(fieldbook.images['icon.'+name]?.file.endsWith('.png'),'missing image icon '+name);
assert.deepEqual(districtOf(1,3),{x:0,y:0});
assert.deepEqual(districtOf(3,3),{x:0,y:0});
assert.deepEqual(districtOf(4,3),{x:1,y:0});
assert.deepEqual(districtOf(0,2),{x:-1,y:0});
assert.ok(plotPosition(4,2).x-plotPosition(3,2).x>plotPosition(3,2).x-plotPosition(2,2).x,'adjacent districts keep a connected path corridor');
assert.deepEqual(districtAtCamera(...Object.values(cameraForDistrict({x:-2,y:3},.82)),.82),{x:-2,y:3});
const stack=new PanelStack();let selected='a';
const node=()=>({active:true,destroy(){this.destroyed=true;}});
const first=stack.push('calendar',node,()=>{selected='a';});
stack.push('confirm',node);stack.push('calendar',node);stack.push('confirm',node);
assert.equal(stack.depth,4,'opening a repeated route must preserve its immediate parent');
stack.back();assert.equal(stack.depth,3);
const old=stack.current;stack.push('calendar',node);
assert.equal(stack.depth,3,'pagination replaces only the top view');assert.equal(old.destroyed,true);
stack.back();selected='b';stack.back();
assert.equal(stack.current,first);assert.equal(selected,'a','back must restore selected field context');
stack.clear();assert.equal(stack.depth,0);assert.equal(first.destroyed,true);
const core=new FarmCore();let obs=await core.start();
const unitCounts=new Map();for(const p of obs.game.economy.farm.plots){const d=districtOf(p.x,p.y),key=d.x+','+d.y;unitCounts.set(key,(unitCounts.get(key)??0)+1);}
assert.ok([...unitCounts.values()].every(count=>count===9),'each initialized district must contain exactly nine plots');
assert.ok(obs.game.economy.farm.plots.some(p=>p.id==='p0q2'&&p.reachable),'farm frontier must extend west across a district edge');
assert.ok(obs.game.actions.some(a=>a.id==='economy:farmexplore:p0q2'),'the west frontier must remain actionable');
const frontierCore=new FarmCore();let frontier=await frontierCore.start();
const west=frontier.game.actions.find(a=>a.id==='economy:farmexplore:p0q2');
assert.ok(west?.enabled,'westward exploration must be available in a new game');
frontier=await frontierCore.act(west.id);
assert.ok(frontier.game.economy.farm.plots.some(p=>p.id==='p-1q2'&&p.reachable),'exploring a boundary plot must create the next district frontier');
assert.equal(frontier.game.economy.farm.plots.filter(p=>districtOf(p.x,p.y).x===-1&&districtOf(p.x,p.y).y===0).length,9,'an expanded district must contain exactly nine plots');
assert.ok((await new FarmCore().start(frontierCore.save())).game.economy.farm.plots.some(p=>p.id==='p-1q2'),'signed-coordinate districts must survive save loading');
const before=obs.game.life.calendar.absoluteDay;
const plan=obs.game.actions.find(a=>a.id.startsWith('economy:plotplan:p2q2-add-')&&a.enabled);
assert.ok(plan,'new game must expose a plan');
obs=await core.act(plan.id);
assert.equal(obs.game.life.calendar.absoluteDay,before,'planning must not advance date');
const tasks=obs.game.economy.farm.schedule.tasks;
assert.ok(tasks.length>=2,'plan should expose sowing and harvest tasks');
assert.ok(tasks.every(t=>!taskView(t,obs).ready),'future tasks must not execute');
assert.ok(!playerText(tasks[0].name).includes('p2q2'),'task name must not expose plot IDs');
const task=tasks.find(t=>t.kind==='harvest');
const fake=structuredClone(obs);const fakeTask={...task,due:true,deadline:before+100,gaps:[]};
fake.game.actions.push({id:'test-action',enabled:true});fakeTask.actionId='test-action';
assert.equal(taskView(fakeTask,fake).ready,false,'harvest task must not trigger sowing on an empty field');
const plot=fake.game.economy.farm.plots.find(p=>p.id===task.plotId);
plot.field={crop:'wheat'};plot.maturity={days:0};
assert.equal(taskView(fakeTask,fake).ready,true,'matching mature harvest can proceed');
fakeTask.deadline=before;
assert.equal(taskView(fakeTask,fake).status,'已过期','deadline is exclusive');
fakeTask.deadline=before+10;fakeTask.gaps=['缺少条件'];
assert.equal(taskView(fakeTask,fake).ready,false,'task blockers must prevent execution');
assert.ok(!actionSummary({id:'economy:farmplot:p2q2-wheat',description:'收获作物。 行动耗费1天（生活页可调整采购）。'}).includes('生活页'));
const warning='此行动将跨过农时截止：p2q2 小麦。';
assert.ok(actionSummary({id:'economy:test:x',description:warning+' 行动耗费1天'}).includes('农时截止'),'deadline warnings must survive cleanup');
const saved=core.save(),restored=new FarmCore();const loaded=await restored.start(saved);
assert.deepEqual(loaded.game.economy.farm.schedule.tasks,obs.game.economy.farm.schedule.tasks,'existing save format must roundtrip');
assert.equal(MAP_LAYOUT.stepX,58,'legacy tile geometry must survive the move to current/');
assert.equal(boardTileSlot({id:HOME_PLOT_ID}),'board.home');
assert.equal(viewTitle(undefined),'田院');
const hudBoard=buildHudViewModel(obs,HOME_PLOT_ID,true);
assert.equal(hudBoard.field,'院前田');
assert.equal(hudBoard.thumbnail,'board.home','the home plot thumbnail must use the homestead slot');
assert.equal(hudBoard.next,nextTaskText(true,obs.game.economy.farm.schedule.tasks,obs));
assert.ok(hudBoard.money.startsWith('钱 ')&&hudBoard.date.length>0);
const hudPlain=buildHudViewModel(obs,HOME_PLOT_ID,false);
assert.equal(hudPlain.thumbnail,boardTileSlot(obs.game.economy.farm.plots.find(p=>p.id===HOME_PLOT_ID)));
const hudMissing=buildHudViewModel(obs,'p99q99',true);
assert.equal(hudMissing.field,'地块单元','an unknown selection must fall back to the unit label');
assert.equal(hudMissing.detail,'未探索');
assert.ok(WORLD_VIEW_VERSIONS.some(v=>v.id==='current'),'the registry catalog must list the current map version');
const registry=new WorldViewRegistry();
const stubView={render(){},hitTest:()=>null,focusPlot:()=>null,focusDistrict:()=>({x:0,y:0,zoom:1}),getCamera:()=>({x:0,y:0,zoom:1}),setCamera(){},resize(){},dispose(){}};
registry.register({id:'current',name:'田格手账',create:async()=>stubView});
assert.deepEqual(registry.list(),[{id:'current',name:'田格手账'}]);
assert.equal(await registry.create('current',null),stubView);
await assert.rejects(()=>registry.create('scenic',null),/Unknown world view version/);
const store=new Map(),storage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,v)};
const prefs=new WorldViewPreferences(storage);
assert.equal(prefs.preferredVersion(),'current');
store.set(WORLD_VIEW_PREFERENCES_KEY,'{corrupt');
assert.equal(prefs.preferredVersion(),'current','corrupt preference JSON must fall back to the current version');
prefs.rememberCamera('current',{x:12,y:-34,zoom:1.2});
assert.deepEqual(prefs.cameraFor('current'),{x:12,y:-34,zoom:1.2});
prefs.selectVersion('scenic');
assert.equal(prefs.preferredVersion(),'scenic');
assert.ok([...store.keys()].every(k=>k===WORLD_VIEW_PREFERENCES_KEY),'world preferences must only write their own key');
store.set(WORLD_VIEW_PREFERENCES_KEY,JSON.stringify({version:42,cameras:{current:{x:'bad',y:1,zoom:2},scenic:{x:1,y:2,zoom:3}}}));
assert.equal(prefs.preferredVersion(),'current','a non-string version must fall back');
assert.equal(prefs.cameraFor('current'),undefined,'non-numeric camera entries must be discarded');
assert.deepEqual(prefs.cameraFor('scenic'),{x:1,y:2,zoom:3});
console.log('UI regression checks passed: 3x3 districts, signed expansion and save, plan/date, task routing and guards, P1 world-view isolation.');
