import assert from 'node:assert/strict';
import {build} from 'esbuild';
async function moduleAt(entry){const result=await build({entryPoints:[entry],bundle:true,write:false,platform:'node',format:'esm',target:'node24'});return import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));}
const {FarmCore}=await moduleAt('core/bridge.ts');
const {taskView,playerText,actionSummary}=await moduleAt('assets/scripts/view/FarmPresentation.ts');
const {PanelStack}=await moduleAt('assets/scripts/view/PanelStack.ts');
const stack=new PanelStack();let selected='a';
const node=()=>({active:true,destroy(){this.destroyed=true;}});
const first=stack.push('calendar',node,()=>{selected='a';});
stack.push('confirm',node);stack.push('calendar',node);stack.push('confirm',node);
assert.equal(stack.depth,4,'opening a repeated route must preserve its immediate parent');
stack.back();assert.equal(stack.depth,3);
const old=stack.current;stack.push('calendar',node);
assert.equal(stack.depth,3,'pagination replaces only the top view');assert.equal(old.destroyed,true);
stack.back();selected='b';stack.back();
assert.equal(stack.current,first);assert.equal(selected,'a','back must restore selected field context');
stack.clear();assert.equal(stack.depth,0);assert.equal(first.destroyed,true);
const core=new FarmCore();let obs=await core.start();
const before=obs.game.life.calendar.absoluteDay;
const plan=obs.game.actions.find(a=>a.id.startsWith('economy:plotplan:p2q2-add-')&&a.enabled);
assert.ok(plan,'new game must expose a plan');
obs=await core.act(plan.id);
assert.equal(obs.game.life.calendar.absoluteDay,before,'planning must not advance date');
const tasks=obs.game.economy.farm.schedule.tasks;
assert.ok(tasks.length>=2,'plan should expose sowing and harvest tasks');
assert.ok(tasks.every(t=>!taskView(t,obs).ready),'future tasks must not execute');
assert.ok(!playerText(tasks[0].name).includes('p2q2'),'task name must not expose plot IDs');
const task=tasks.find(t=>t.kind==='harvest');
const fake=structuredClone(obs);const fakeTask={...task,due:true,deadline:before+100,gaps:[]};
fake.game.actions.push({id:'test-action',enabled:true});fakeTask.actionId='test-action';
assert.equal(taskView(fakeTask,fake).ready,false,'harvest task must not trigger sowing on an empty field');
const plot=fake.game.economy.farm.plots.find(p=>p.id===task.plotId);
plot.field={crop:'wheat'};plot.maturity={days:0};
assert.equal(taskView(fakeTask,fake).ready,true,'matching mature harvest can proceed');
fakeTask.deadline=before;
assert.equal(taskView(fakeTask,fake).status,'已过期','deadline is exclusive');
fakeTask.deadline=before+10;fakeTask.gaps=['缺少条件'];
assert.equal(taskView(fakeTask,fake).ready,false,'task blockers must prevent execution');
assert.ok(!actionSummary({id:'economy:farmplot:p2q2-wheat',description:'收获作物。 行动耗费1天（生活页可调整采购）。'}).includes('生活页'));
const warning='此行动将跨过农时截止：p2q2 小麦。';
assert.ok(actionSummary({id:'economy:test:x',description:warning+' 行动耗费1天'}).includes('农时截止'),'deadline warnings must survive cleanup');
const saved=core.save(),restored=new FarmCore();const loaded=await restored.start(saved);
assert.deepEqual(loaded.game.economy.farm.schedule.tasks,obs.game.economy.farm.schedule.tasks,'existing save format must roundtrip');
console.log('UI regression checks passed: plan/date, task routing and guards, deadline, copy and save compatibility.');
